#!/usr/bin/env python3
"""Backfill contextual embeddings for existing cases.

Re-embeds existing case chunks with contextual prefixes generated by Flash LLM.
This improves retrieval quality by prepending document-level context to each chunk.

Usage:
    python scripts/backfill_contextual_embeddings.py --batch-size 50 --dry-run
    python scripts/backfill_contextual_embeddings.py --batch-size 100
"""
from __future__ import annotations

import argparse
import asyncio
import logging
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from sqlalchemy import text

from app.db.postgres import async_session_factory

logger = logging.getLogger(__name__)


async def backfill_case(
    case_id: str,
    db,
    embedder,
    vector_store,
    flash_llm,
    dry_run: bool = False,
) -> dict:
    """Backfill contextual embeddings for a single case."""
    from app.core.ingestion.contextual_embeddings import batch_contextualize_chunks

    stats = {"chunks": 0, "embedded": 0, "errors": 0}

    # Load case metadata
    result = await db.execute(
        text("SELECT title, citation, court, year FROM cases WHERE id = :id"),
        {"id": case_id},
    )
    row = result.fetchone()
    if not row:
        return stats

    doc_meta = {
        "title": row[0] or "",
        "citation": row[1] or "",
        "court": row[2] or "",
        "year": row[3] or 0,
    }

    # Load existing chunks from vector store metadata
    # We query Pinecone by case_id filter to get existing chunk texts
    try:
        existing = await vector_store.query_by_metadata(
            {"case_id": case_id}, top_k=500
        )
    except Exception:
        # Fallback: load from case_sections table
        sections_result = await db.execute(
            text(
                "SELECT section_type, content FROM case_sections "
                "WHERE case_id = :case_id ORDER BY section_index"
            ),
            {"case_id": case_id},
        )
        existing = []
        for sec_row in sections_result.fetchall():
            existing.append({"text": sec_row[1], "section_type": sec_row[0]})

    if not existing:
        return stats

    chunk_dicts = []
    for item in existing:
        text_content = item.get("metadata", {}).get("text", "") if isinstance(item, dict) and "metadata" in item else item.get("text", "")
        if text_content:
            chunk_dicts.append({"text": text_content})

    stats["chunks"] = len(chunk_dicts)

    if dry_run:
        logger.info("[DRY RUN] case_id=%s: would backfill %d chunks", case_id, len(chunk_dicts))
        return stats

    # Generate contextual prefixes
    contextualized = await batch_contextualize_chunks(
        chunk_dicts, doc_meta, flash_llm, document_type="case_law"
    )

    # Re-embed and upsert
    texts = [c["contextualized_text"] for c in contextualized]
    try:
        embeddings = await embedder.embed_batch(texts)
        vectors = []
        for i, (chunk, emb) in enumerate(zip(contextualized, embeddings, strict=False)):
            vectors.append({
                "id": f"{case_id}_{i}",
                "values": emb,
                "metadata": {
                    "case_id": case_id,
                    "chunk_index": i,
                    "document_type": "case_law",
                    "text": chunk["text"][:2000],
                },
            })
        for j in range(0, len(vectors), 100):
            await vector_store.upsert(vectors[j:j + 100])
        stats["embedded"] = len(vectors)
    except Exception as exc:
        logger.error("Backfill embedding failed for case_id=%s: %s", case_id, exc)
        stats["errors"] = 1

    return stats


async def main(args: argparse.Namespace) -> None:
    logging.basicConfig(level=logging.INFO, format="%(asctime)s %(levelname)s %(message)s")

    async with async_session_factory() as db:
        # Get all completed cases
        result = await db.execute(
            text(
                "SELECT id FROM cases WHERE ingestion_status = 'complete' "
                "ORDER BY created_at LIMIT :limit"
            ),
            {"limit": args.limit or 100000},
        )
        case_ids = [str(row[0]) for row in result.fetchall()]

    logger.info("Found %d cases to backfill", len(case_ids))

    if not case_ids:
        return

    # Initialize dependencies
    embedder = None
    vector_store = None
    flash_llm = None

    if not args.dry_run:
        try:
            from app.core.dependencies import get_embedder, get_flash_llm, get_vector_store
            embedder = get_embedder()
            vector_store = get_vector_store()
            flash_llm = get_flash_llm()
        except Exception as exc:
            logger.error("Failed to initialize dependencies: %s", exc)
            return

    total = {"chunks": 0, "embedded": 0, "errors": 0}
    batch_size = args.batch_size

    async with async_session_factory() as db:
        for i in range(0, len(case_ids), batch_size):
            batch = case_ids[i:i + batch_size]
            for cid in batch:
                stats = await backfill_case(
                    cid, db, embedder, vector_store, flash_llm,
                    dry_run=args.dry_run,
                )
                for k in total:
                    total[k] += stats[k]

            logger.info(
                "Progress: %d/%d cases, %d chunks embedded, %d errors",
                min(i + batch_size, len(case_ids)),
                len(case_ids), total["embedded"], total["errors"],
            )

    logger.info("=== BACKFILL COMPLETE ===")
    logger.info("Total: %d chunks, %d embedded, %d errors",
                total["chunks"], total["embedded"], total["errors"])


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Backfill contextual embeddings")
    parser.add_argument("--batch-size", type=int, default=50, help="Cases per batch")
    parser.add_argument("--limit", type=int, default=None, help="Max cases to process")
    parser.add_argument("--dry-run", action="store_true", help="Parse only, no writes")
    asyncio.run(main(parser.parse_args()))
